### PR TITLE
Add support for roles, multiple algorithms & raw JWKS endpoint

### PR DESCRIPTION
**Pull request by kdubb**
## Roles
* Each role requires a "subject" which becomes the token "sub" claim
* * Must match the "subject_pattern" configuration
* * Subject can no longer be provdide during sign operation
* Roles can also specify "other" claims
* * Must be explicitly allowed via "allowed_claims" configuration

## RSA & EC keys/algorithms support
* `sig_alg` configuraiton selects signature algorithm and key type
* * Accepts `ES256`, `ES384`, `ES512`, `RS256`, `RS384`, `RS512`
* `key_size_bits` determines size of generated RSA keys
* * Accepts `2048`, `3072`, and `4096`
* * Only used for RSA signature algorithms

## JWKS endpoint
Reading from the `jwks` endpoint now returns a standard `application/jwk-set+json` response (with explicitly set Content-Type header) to allow other services to validate JWTs without change.

### CODE REVIEW

**Comment by kdubb** [comment]
@ian-fox We're in the process of evaluating/implementing our updated version of this plugin in our platform. I figured I'd make a PR back to you even though your project appears to be abandoned. Let me know your level of interest is merging these Changes.

**Comment by ian-fox** [comment]
I will have a look after dinner, thank you so much!

I think I missed a few PRs while I was burnt out and not checking GitHub, which I regret, hoping I can start being more active again though.

**Comment by kdubb** [comment]
Some other notable changes...

#### FriendlyId
Switched to generating friendly ids, they're uuids with a lot shorter encoding and are better in urls.

#### TTL Change updates Keys
Changing either ttl in the config now updates the previously generated keys. This is to ensure that changing the rotation period takes effect "when expected". Previously rotation wouldn't happen until the period that was configured when the key was generated expired.

 Care is taken to ensure the `KeepUntil` is never reduced and therefore can never be pruned before all JWTs are expired.

**Comment by ian-fox** [comment]
Wow you guys have done great work on this! Now that github has the archive feature I think what I might actually do is update the readme to point people to your version, and archive this one as you're clearly doing a much better job maintaining it than I am 😅 

Originally I made it just as a toy project to learn about the vault ecosystem, but I'm glad you were able to get some use out of it!

**Pull request closed without merging**
